### ISSUE TITLE
No Log is comming 

### ISSUE THREAD

**Issue by shaurya11123** [ScreamsLover/Discord-phishing-leak#1]
Hi, i HOSTED THIS SCRIPT ON REPLIT COZ I AM NOT REALLY PRO IN COMPUTER THING 
THE HOSTING AND THE LOGIN PADE WORKS FINE 
![image](https://user-images.githubusercontent.com/77480523/151511749-fe09a524-0b35-4e21-98ff-9cf232a16988.png)
BUT WHEN I TRY THIS ON MY PC I LOGIN ON THAT PHISHING WITH WRITE CREDENTIALS ( I USE CUSTOM DOMAIN)
I HAVE LOGGED IN TO DISCORD PC AND WEB IDK HOW IT STEALS THE TOKEN I LOGIN W8 SOMETIME BUT NO OUTOUT COMES
![image](https://user-images.githubusercontent.com/77480523/151511975-3c1adf33-91a7-4cf5-bb0d-df0427bbbaf1.png)
SEE THIS CONFIG ON THE ABOVE PIC
I ALSO USED INFINITY FREE HOSTING THE SITE WORKED FINE BT NO LOG STILL
![image](https://user-images.githubusercontent.com/77480523/151512301-d5aca897-fb2f-4fc8-8070-ca7b4d0754c1.png)

MY REPEL https://replit.com/join/eedgiylufx-shauryavr 
PLS FIX AND CONTACT ME 

HOPING FOR HELP

**Comment by ScreamsLover** [comment]
hey sorry but currently the website and all the project is discontinued, if you can fix it yourself.
